In [ ]:
Types of Imputer 

Simple Imputer  => 
                    SimpleImputer is also handle missing values and replace missing values, 
                    example :- mean, median, most frequent, ya constant value.

                        
KNNImputer    =>
                KNNImputer is also handle  missing values and  use K-Nearest Neighbors algorithm and replace value. 
                This method is also match dataset on thier similar points and  estimate missing values.

IterativeImputer =>
                 IterativeImputer is also handle  missing values use with multiple regression models and predict data.
                  every  feature and thier missing values   predict iteratively data.

In [7]:
from sklearn.impute import SimpleImputer
import numpy as np
import pandas as pd
a = np.array([[np.nan,2,5],[6,np.nan,20],[34,4,np.nan]])
a
# use SimpleImputer
# Imputer with mean strategy
imputer = SimpleImputer(strategy='mean')
imputer = SimpleImputer(strategy='median')    # Imputer with median strategy
imputer = SimpleImputer(strategy='most_frequent')       # Imputer with most_frequent strategy
imputed_data = imputer.fit_transform(a)
print(imputed_data)


[[ 6.  2.  5.]
 [ 6.  2. 20.]
 [34.  4.  5.]]


In [10]:
""" KNNImputer """
from sklearn.impute import KNNImputer
a = np.array([[np.nan,2,5],[6,np.nan,20],[34,4,np.nan]])
a
# use KNNImputer
# Imputer with k=3 neighbors
imputer = KNNImputer(n_neighbors=2)
imputed_data = imputer.fit_transform(a)
imputed_data

array([[20. ,  2. ,  5. ],
       [ 6. ,  3. , 20. ],
       [34. ,  4. , 12.5]])

In [12]:
"""   IterativeImputer """
from sklearn.experimental import enable_iterative_imputer  
from sklearn.impute import IterativeImputer
a
# Iterative Imputer
imputer = IterativeImputer()
imputed_data = imputer.fit_transform(a)
print(imputed_data)

[[60.54045552  2.          5.        ]
 [ 6.          6.11002311 20.        ]
 [34.          4.         12.29929387]]


In [ ]:
 Column Transformer =>
                     Column Transformer its  powerful tool  in scikit-learn library. 
                     its use mostly to connect multipul fetures and prepocess them.it means that you have numerical aur categorical features in your dataset.
                     its mange both features in one frame
                  Column Transformer its decide its self which column  apply in  transformations  . 
                      its helpful to convert numerical features  into scale data and convert categorical features in encode .
        

In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler,OneHotEncoder,LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
df = pd.read_csv(r"C:\Users\Lenovo\Desktop\gaurav\titanic.csv")
df

In [ ]:
 """ Numerical aur Categorical Features Identify karo: """
numerical_features = ['Age', 'Fare', 'SibSp', 'Parch']
categorical_features = ['Sex', 'Embarked', 'Name']

In [ ]:
"""Pipelines :
Numerical Features ke liye:
Missing values ko median se fill karo.
Data ko scale karo (StandardScaler). """
numerical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

""" Categorical Features ke liye:
Missing values ko most frequent value se fill karo.

One-hot encode karo. """
categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])


#Column Transformer Define karo: """
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, numerical_features),
        ('cat', categorical_transformer, categorical_features)
    ]
)

In [ ]:
#Complete Pipeline 
from sklearn.linear_model import LogisticRegression

model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', LogisticRegression())
])

X = df.drop('Survived', axis=1)
y = df['Survived']

# Model Train aur Evaluate
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model.fit(X_train, y_train)

print("Model Accuracy: ", model.score(X_test, y_test))